name: Generic Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '33 18 * * *'
      timezone: 'Europe/Stockholm'


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run script
        run: echo "Scheduled job ran at $(date -u)"

      - name: List files
        run: |
          find .
