name: At Every Push
on: push

jobs:
  clone-and-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: List files
        run: |
          find .
