name: At Every Push
on: push

jobs:
  clone-and-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: echo "Scheduled job ran at $(date -u)"

      - name: List files
        run: |
          find .
